apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  type: NodePort
  ports:
    - name: "30500"
      port: 30500
      targetPort: 5678
      protocol: TCP
  selector:
    service: n8n
